---

# tasks file for webapp
- debug:
    msg: "Launch WEABPP deployment"
  run_once: true

- name: "Template index.html-easter_egg.j2 to index.html on target"
  template:
    src: index.html-easter_egg.j2
    dest: "{{ nginx_root_location }}/index.html"
    mode: 0644
  tags:
    - webapp

- name: "Install unzip package"
  package:
    name: unzip
    state: latest
  tags:
    - webapp

- name: "Unarchive playbook stacker game"
  unarchive:
    src: playbook_stacker.zip
    dest: "{{ nginx_root_location }}"
    mode: 0755
  tags:
    webapp

- name: "Restart nginx"
  service:
    name: nginx
    state: restarted
  register: nginx_start
  notify: Check HTTP Service

- debug:
    msg: "The webapp {{ webapp_name }} is sucessfully deployed on {{ ansible_hostname }}"
  when: nginx_install.state == "started"
  
# Three dots indicate the end of a YAML document
...